import{clamp as E}from"../../libs/math.js";import R from"../../libs/core/dom.js";import{adjustCanvas as B}from"../../libs/dom.js";import"../../libs/class-names.js";import"../../libs/cleanup.js";const M=await R({assetsInfo:[{type:"image",src:import.meta.resolve("./backgroundLayers/layer-1.png",new URL(import.meta.url))},{type:"image",src:import.meta.resolve("./backgroundLayers/layer-2.png",new URL(import.meta.url))},{type:"image",src:import.meta.resolve("./backgroundLayers/layer-3.png",new URL(import.meta.url))},{type:"image",src:import.meta.resolve("./backgroundLayers/layer-4.png",new URL(import.meta.url))},{type:"image",src:import.meta.resolve("./backgroundLayers/layer-5.png",new URL(import.meta.url))}],cb:({appId:s,assets:y,cleanUpManager:o,createLayout:w})=>{const c=`canvas-${s}`,p=1,l=20;let t=5;const g=`showGameSpeed-${s}`,h=`gameSpeed-${s}`,r={render:{width:800,height:700},dom:{}};w(`<canvas
				id="${c}"
				width="${r.render.width}"
				height="${r.render.height}"
				class="border-2 border-solid border-gray-300 dark:border-gray-700 max-w-full mx-auto"
			></canvas>
			<div class="flex flex-col gap-4">
				<label>Game speed: <span id="${g}">${t}</span></label>
				<input type="range" id="${h}" min="${p}" max="${l}" value="${t}" />
			</div>`);const v=document.getElementById(g),f=document.getElementById(h);o.registerEventListener({elem:f,type:"input",listener:e=>{t=E(Number(e.target.value),p,l),v.innerText=t.toString()}});const d=document.getElementById(c);if(!d)throw new Error("Couldn't find the canvas!");const a=d.getContext("2d");if(!a)throw new Error("Couldn't get the canvas context!");const x=B({canvas:d,ctx:a,onUpdateCanvasSize:e=>{r.dom=e}});o.register(x);const[b,L,I,S,$]=y;class n{constructor(i,k){this.x1=0,this.y=0,this.width=i.naturalWidth,this.height=i.naturalHeight,this.img=i,this.speedModifier=k,this.speed=t*this.speedModifier}update(){this.speed=t*this.speedModifier,this.x1<=-this.width&&(this.x1=0),this.x1=Math.floor(this.x1-this.speed)}draw(){a.drawImage(this.img,this.x1,0),a.drawImage(this.img,this.x1+this.width,0)}}const C=[new n(b,.2),new n(L,.4),new n(I,.6),new n(S,.8),new n($,1)];let m;function u(){a.clearRect(0,0,r.render.width,r.render.height);for(const e of C)e.update(),e.draw();m=requestAnimationFrame(u)}o.register(()=>{m&&cancelAnimationFrame(m)}),u()}});export{M as default};
